<?php namespace {

    class Ref
    {
        const PASSWORD_MIN_LENGTH =  8;
        const CLIENT_STATUS_ACTIVE = 'CLIENT_STATUS_ACTIVE';
        const CLIENT_STATUS_FREEZED = 'CLIENT_STATUS_FREEZED';
        const CLIENT_STATUS_DELETED = 'CLIENT_STATUS_DELETED';
        const CLIENT_STATUS_CLIENT = 'CLIENT_STATUS_CLIENT';
        const CLIENT_STATUS_EXPIRED = 'CLIENT_STATUS_EXPIRED';
        const CLIENT_STATUS_PROSPECT = 'CLIENT_STATUS_PROSPECT';
        const CLIENT_STATUS_SUSPECT = 'CLIENT_STATUS_SUSPECT';
        const CLIENT_TYPE_CORPORATE = 'CLIENT_TYPE_CORPORATE';
        const CLIENT_TYPE_HR = 'CLIENT_TYPE_HR';
        const CLIENT_TYPE_OTHER = 'CLIENT_TYPE_OTHER';
        const CLIENT_TYPE_SCHOOL = 'CLIENT_TYPE_SCHOOL';
        const CONTACT_TYPE_FINANCIAL = 'CONTACT_TYPE_FINANCIAL';
        const CONTACT_TYPE_SALES = 'CONTACT_TYPE_SALES';
        const CONTENTS_TYPE_MISSION = 'CONTENTS_TYPE_MISSION';
        const CONTENTS_TYPE_STEP = 'CONTENTS_TYPE_STEP';
        const DEVICE_DESKTOP = 'DEVICE_DESKTOP';
        const DEVICE_MOBILE = 'DEVICE_MOBILE';
        const DEVICE_TABLET = 'DEVICE_TABLET';
        const INTERFACE_DEFAULT = 'INTERFACE_DEFAULT';
        const INTERFACE_FRONT = 'INTERFACE_FRONT';
        const INTERFACE_JOBMAKER = 'INTERFACE_JOBMAKER';
        //Dedicated for demo from partner
        const INTERFACE_JOBMAKER_DEMO = 'INTERFACE_JOBMAKER_DEMO';
        const INTERFACE_PARTNER = 'INTERFACE_PARTNER';


        const API_PARTNER = 'api-partner';
        const API_ADMIN = 'api-admin';
        const API_OPERATOR = 'api-operator';
        const API_JMAKER = 'api-jmaker';

        const API_OPERATOR_GUARD = 'api-operator-guard';
        const API_FRONT_GUARD = 'api-front-guard';

        const INVOICE_STATUS_CANCEL = 'INVOICE_STATUS_CANCEL';
        const INVOICE_STATUS_INVOICE = 'INVOICE_STATUS_INVOICE';
        const INVOICE_STATUS_PAID = 'INVOICE_STATUS_PAID';
        const INVOICE_STATUS_PURCHASE_ORDER = 'INVOICE_STATUS_PURCHASE_ORDER';
        const JOBMAKER_GRADE_1 = 'JOBMAKER_GRADE_1';
        const JOBMAKER_GRADE_2 = 'JOBMAKER_GRADE_2';
        const JOBMAKER_GRADE_3 = 'JOBMAKER_GRADE_3';
        const JOBMAKER_GRADE_4 = 'JOBMAKER_GRADE_4';
        const JOBMAKER_GRADE_5 = 'JOBMAKER_GRADE_5';
        const JOBMAKER_GRADE_6 = 'JOBMAKER_GRADE_6';
        const JOBMAKER_LOOKINGFOR_EMPLOYEE = 'JOBMAKER_LOOKINGFOR_EMPLOYEE';
        const JOBMAKER_SITUATION_THINK = 'JOBMAKER_SITUATION_THINK';
        const JOBMAKER_SITUATION_WISH = 'JOBMAKER_SITUATION_WISH';
        const LANG_EN = 'LANG_EN';
        const LANG_FR = 'LANG_FR';
        const LANG_DEBUG = 'LANG_DEBUG';
        const MAIL_STATUS_CREATED = 'MAIL_STATUS_CREATED';
        const MAIL_STATUS_ERROR = 'MAIL_STATUS_ERROR';
        const MAIL_STATUS_OPENED = 'MAIL_STATUS_OPENED';
        const MAIL_STATUS_PROCESSING = 'MAIL_STATUS_PROCESSING';
        const MAIL_STATUS_SENT = 'MAIL_STATUS_SENT';
        const MEDIA_TYPE_AVATAR = 'MEDIA_TYPE_AVATAR';
        const MEDIA_TYPE_PARTNER = 'MEDIA_TYPE_PARTNER';
        const MISSION_TYPE_SERVICE = 'MISSION_TYPE_SERVICE';
        const MISSION_TYPE_WORKSHOP = 'MISSION_TYPE_WORKSHOP';
        const PRODUCTION_STATUS_DRAFT = 'PRODUCTION_STATUS_DRAFT';
        const PRODUCTION_STATUS_PUBLISHED = 'PRODUCTION_STATUS_PUBLISHED';
        const PRODUCTION_STATUS_VALID = 'PRODUCTION_STATUS_VALID';
        const PRODUCTION_TYPE_ADVICES = 'PRODUCTION_TYPE_ADVICES';
        const PRODUCTION_TYPE_CAP_QUESTION = 'PRODUCTION_TYPE_CAP_QUESTION';
        const PRODUCTION_TYPE_CHECKUP = 'PRODUCTION_TYPE_CHECKUP';
        const PRODUCTION_TYPE_CHOICES = 'PRODUCTION_TYPE_CHOICES';
        const PRODUCTION_TYPE_CHOICES_ANSWERS = 'PRODUCTION_TYPE_CHOICES_ANSWERS';
        const PRODUCTION_TYPE_DETOX_COMMENT = 'PRODUCTION_TYPE_DETOX_COMMENT';
        const PRODUCTION_TYPE_FORMULATION = 'PRODUCTION_TYPE_FORMULATION';
        const PRODUCTION_TYPE_JOB = 'PRODUCTION_TYPE_JOB';
        const PRODUCTION_TYPE_MAIL = 'PRODUCTION_TYPE_MAIL';
        const PRODUCTION_TYPE_MOTTO = 'PRODUCTION_TYPE_MOTTO';
        const PRODUCTION_TYPE_NETWORK = 'PRODUCTION_TYPE_NETWORK';
        const PRODUCTION_TYPE_PITCH = 'PRODUCTION_TYPE_PITCH';
        const PRODUCTION_TYPE_PROJECT = 'PRODUCTION_TYPE_PROJECT';
        const PRODUCTION_TYPE_REALISATION = 'PRODUCTION_TYPE_REALISATION';
        const PRODUCTION_TYPE_SOCIAL = 'PRODUCTION_TYPE_SOCIAL';
        const PRODUCTION_TYPE_STRENGTH = 'PRODUCTION_TYPE_STRENGTH';
        const PRODUCTION_TYPE_UNSTUCK_DEVISE = 'PRODUCTION_TYPE_UNSTUCK_DEVISE';
        const RUN_STATUS_ACCESSIBLE = 'RUN_STATUS_ACCESSIBLE';
        const RUN_STATUS_ARCHIVED = 'RUN_STATUS_ARCHIVED';
        const RUN_STATUS_FINISHED = 'RUN_STATUS_FINISHED';
        const RUN_STATUS_HIDDEN = 'RUN_STATUS_HIDDEN';
        const RUN_STATUS_INPROGRESS = 'RUN_STATUS_INPROGRESS';
        const RUN_STATUS_VISIBLE = 'RUN_STATUS_VISIBLE';
        const RUN_STATUS_FINISHED_CHECKUP_WITH_JOBMAKER = 'RUN_STATUS_FINISHED_CHECKUP_WITH_JOBMAKER';

        const MEETING_TYPE_INVITATION = 'MEETING_TYPE_INVITATION';
        const MEETING_TYPE_SCHEDULED = 'MEETING_TYPE_SCHEDULED';

        const INVIATION_GOAL_DELAY_QUICKLY = 'GOAL_DELAY_QUICKLY';
        const INVIATION_GOAL_DELAY_SIX_MONTH = 'GOAL_DELAY_SIX_MONTH';
        const INVIATION_GOAL_DELAY_ONE_YEAR = 'GOAL_DELAY_ONE_YEAR';
        const INVIATION_GOAL_DELAY_HEIGHTEEN_MONTH = 'GOAL_DELAY_HEIGHTEEN_MONTH';
        const INVIATION_GOAL_NOT_DEFINE = 'GOAL_NOT_DEFINE';

        //CONSTANT USED TO DEFINE CGU TYPE
        const CGU_TYPE_JOBMAKER =  'CGU_TYPE_JOBMAKER';
        const CGU_TYPE_CLIENT =  'CGU_TYPE_CLIENT';
        const CGU_TYPE_HOLDING =  'CGU_TYPE_HOLDING';


        //EVENTS
        const EVENT_MAIL_PRESCRIBER_TO_JMAKER = 'EVENT_MAIL_PRESCRIBER_TO_JMAKER';
        const EVENT_SUBSCRIPTION_FOLLOW_UP_PRESCRIBER_TO_JMAKER = 'EVENT_SUBSCRIPTION_FOLLOW_UP_PRESCRIBER_TO_JMAKER';
        const EVENT_MAIL_NOTIFICATIONS_UNSUBSCRIPTION = 'EVENT_MAIL_NOTIFICATIONS_UNSUBSCRIPTION ';
        const EVENT_MAIL_NOTIFICATIONS_SUBSCRIPTION = 'EVENT_MAIL_NOTIFICATIONS_SUBSCRIPTION ';
        const EVENT_SHARED_SYNTHESIS = 'EVENT_SHARED_SYNTHESIS';

        //REF
        const REF_PRESCRIBER = 'REF_PRESCRIBER';
        const REF_MAIL = 'REF_MAIL';

        //SCOPE
        const SCOPE_JMAKER = 'SCOPE_JMAKER';
        const SCOPE_CLIENT = 'SCOPE_CLIENT';
        const SCOPE_TECHNICAL = 'SCOPE_TECHNICAL';

        //EVENT
        public const EVENT_TYPE_JMAKER_INVITED = "EVENT_TYPE_JMAKER_INVITED";
        public const EVENT_TYPE_ONBOARDED = "EVENT_TYPE_ONBOARDED";
        public const EVENT_TYPE_STARTED = "EVENT_TYPE_STARTED";
        public const EVENT_TYPE_UPDATED = "EVENT_TYPE_UPDATED";
        public const EVENT_TYPE_FINISHED = "EVENT_TYPE_FINISHED";

        //NOTIFICATION SUBSCRIPTION
        public const NOTIFICATION_SUBSCRIPTION_REMINDER_1 = 'NOTIF_REMINDER_1';
        public const NOTIFICATION_SUBSCRIPTION_EXPLOITS = 'NOTIF_REMINDER_EXPLOITS';
        public const NOTIFICATION_SUBSCRIPTION_REMINDER_2 = 'NOTIF_REMINDER_2';
        public const NOTIFICATION_SUBSCRIPTION_CHOICE = 'NOTIF_REMINDER_CHOICE';
        public const NOTIFICATION_SUBSCRIPTION_REMINDER_3 = 'NOTIF_REMINDER_3';


        //Patch
        public const LANGUAGE_GROUP_JOBMAKER_UUID = 'C7C9AFEF41034E479332C739F9A39144';
        public const LANGUAGE_GROUP_PARTNER_UUID = '2E5451D4B30F422697F963F895786E76';
        public const LANGUAGE_GROUP_FRONT_UUID = '9D52DD7100CD4424AA3F89D762FEAC7E';
        public const LANGUAGE_GROUP_NEXT_MOVE_UUID = 'E932F112DAA94812950DD94F8F21A9B6';
        public const LANGUAGE_GROUP_NEXT_MOVE_INSIDE_UUID = '60A734A22965455FB036D30CC975EE56';
        public const LANGUAGE_GROUP_I_1_UUID = '32F6B17ECB854A60860E108300B2C7FC';
        public const LANGUAGE_GROUP_I_2_UUID = 'DAF5799812CE4367A839BAC897751910';
        public const LANGUAGE_GROUP_II_1_UUID = 'C854F1DFC1EE4B43B2AC2CAA2099FD05';
        public const LANGUAGE_GROUP_II_2_UUID = '4F76FC40E3644B5BB40C9CDF7E9F7210';
        public const LANGUAGE_GROUP_II_3_UUID = '223848F814E34896AEAB7247D8BE4D8E';
        public const LANGUAGE_GROUP_II_4_UUID = 'C09B1304BF514329B900A620A240AB96';
        public const LANGUAGE_GROUP_III_1_UUID = 'B6DE9F4A69A145E8AC2DFD5A0F92669B';
        public const LANGUAGE_GROUP_III_2_UUID = 'BD3DB6C6197540FEAA0616C740259263';
        public const LANGUAGE_GROUP_IV_1_UUID = '221723CEEB2A4143B3FE6EE434552CC8';
        public const LANGUAGE_GROUP_CLIENT_TOTAL_UUID = '92B48CDE9B4549EDAADE855AC3BBC944';
        public const LANGUAGE_GROUP_CLIENT_CACIB_UUID = '00000000000000000000000000000000';


        //JMAKER STATE
        public const JMAKER_STATE_INVITED = 'JMAKER_STATE_INVITED';
        public const JMAKER_STATE_ONBOARDING = 'JMAKER_STATE_ONBOARDING';
        public const JMAKER_STATE_ACTIVE = 'JMAKER_STATE_ACTIVE';
        public const JMAKER_STATE_ARCHIVED = 'JMAKER_STATE_ARCHIVED';


        //PRESCRIBER STATE
        public const PRESCRIBER_STATE_INVITED = 'PRESCRIBER_STATE_INVITED';
        public const PRESCRIBER_STATE_ONBOARDING = 'PRESCRIBER_STATE_ONBOARDING';
        public const PRESCRIBER_STATE_ACTIVE = 'PRESCRIBER_STATE_ACTIVE';
        public const PRESCRIBER_STATE_ARCHIVED = 'PRESCRIBER_STATE_ARCHIVED';

        //PRESCRIBER TEMPLATE TYPE
        public const PRESCRIBER_RELANCE = 'PRESCRIBER_RELANCE';

        //CLIENT TEMPLATE TYPE
        public const CLIENT_RELANCE = 'CLIENT_RELANCE';


    }
}
